config/routes.rb
Rails.application.routes.draw do

  root 'blog#index'
  get 'about' => 'blog#about'

  resources :articles


end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3, maximum: 15}
  validates :description, presence: true,length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit,:show,:update, :destroy]

  def index
    @articles = Article.all

  end

  def new
    @article = Article.new
  end

  def create
    # render plain: params[:article].inspect
    # @article.save
    # redirct_to article_path(@article)
    @article = Article.new(article_param)
    if @article.save
      flash[:success] = "El articulo fue creado correctamente"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show
    # @article = Article.find(params[:id])
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_param)
      flash[:success] = " El articul fue correctamente actualizado";
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "El articulo fue eliminado"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_param
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index

  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
            <div class="form-group">
              <div class="control-label col-sm-2">
                <%= f.label :title %><br/>
              </div>
              <div class="col-md-8">
                <%= f.text_field :title, class: 'form-control', placeholder: 'Titulo del articulo',autofocus: true %>
              </div>
            </div>
            <div class="form-group">
              <div class="control-label col-sm-2">
                <%= f.label :description %><br/>
              </div>
              <div class="col-md-8">
                  <%= f.text_area :description,rows:10,  class: 'form-control', placeholder: 'Cuerpo del articulo' %>
              </div>
            </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
          </div>
        </div>
    <% end %>
    <div class='col-xs-4 col-xs-offset-4'>
      [<%= link_to 'Cancel request and return to articles',articles_path %>]
    </div>

  </div>
</div>

app/views/articles/edit.html.erb
<h2 align="center">Editanto el articulo selecionado</h2>

<%= render "form" %>

app/views/articles/index.html.erb
<h2 align="center">Lista de articulos</h2>
<% @articles.each do |article| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="article-title">
        <%=  link_to article.title,article_path(article) %>
        </div>
      <div class="article-body">
        <%= truncate(article.description, length: 100) %>
      </div>
      <div class="article-actions">
        <%= link_to 'Editar',edit_article_path(article), class: 'btn btn-xs btn-primary' %>
        <%= link_to 'Delete', article_path(article),
                    method: :delete,
                    data: { confirm: 'Estas seguro ?' },
                    class: 'btn btn-xs btn-danger' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/articles/new.html.erb
<h2 align="center">Nuevo Articulo</h2>

<%= render "form" %>

app/views/articles/show.html.erb
<h2 align="center">
  Title <%= @article.title %>
</h2>
<div class="well col-xs colxs-offset-2">
  <h4 class="center description">
    <strong>
      Description
    </strong>
  </h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class="article-actions">
    <%= link_to 'Editar',edit_article_path(@article), class: 'btn btn-xs btn-primary' %>
    <%= link_to 'Delete', article_path(@article),
                method: :delete,
                data: { confirm: 'Estas seguro ?' },
                class: 'btn btn-xs btn-danger' %>
    <%= link_to 'Ver todos los articulos',articles_path, class: 'btn btn-xs btn-success' %>
  </div>
</div>

app/views/blog/about.html.erb
<h2>About Page</h2>

<%= link_to "Mundix Blog",articles_path %> | <%= link_to "Home",root_path %>

app/views/blog/index.html.erb
<div class="center jumbotron">
  <h1>Mundi Blog</h1>
  <%= link_to "Sign up now","#", class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer>
    <small>Copyrights &copy; <a href="http://mundixblog.herokuapp.com">Mundiblog</a>
    By <a href="#">Clemente Pichardo</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "Nosotros",about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">
          &#215;
        </a>
        <%= content_tag :div, msg, :id=> "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" id="logo" href="">MundiBlog</a>-->
      <%= link_to "Alpha blog", root_path, class: "navbar-brand",id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articulos",articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Acciones <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><%= link_to "Crear Articulo",new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mundixblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>

<div class="container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count,"Error") %>
              Estos errores previenen salvar el articulo:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li>
                      <%= msg %>
                    </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>